spring.application.name=${SPRING_APPLICATION_NAME:chats}
server.port=${SERVER_PORT:8098}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:LaCuenta}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:root}}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

lc.middleware.url=${LC_MIDDLEWARE_URL:http://localhost:8097}
lc.middleware.argentinadatos.cotizaciones.dolares.path=${LC_MIDDLEWARE_ARGENTINADATOS_COTIZACIONES_DOLARES_PATH:/v1/argentinadatos/cotizaciones/dolares}
lc.middleware.argentinadatos.finanzas.indices.inflacion.path=${LC_MIDDLEWARE_ARGENTINADATOS_FINANZAS_INDICES_INFLACION_PATH:/v1/argentinadatos/finanzas/indices/inflacion}
lc.middleware.argentinadatos.finanzas.indices.inflacion.interanual.path=${LC_MIDDLEWARE_ARGENTINADATOS_FINANZAS_INDICES_INFLACION_INTERANUAL_PATH:/v1/argentinadatos/finanzas/indices/inflacion-interanual}
lc.middleware.argentinadatos.finanzas.indices.riesgo.pais.path=${LC_MIDDLEWARE_ARGENTINADATOS_FINANZAS_INDICES_RIESGO_PAIS_PATH:/v1/argentinadatos/finanzas/indices/riesgo-pais}

lc.library.sync.cron=${LC_LIBRARY_SYNC_CRON:0 0 1 * * *}
